<div style="direction:rtl;line-height:300%;">
<div align=center>
<font face="B Nazanin" size=3>
    به نام خدا
    </font>
    <br>
    <br>
    <font face="B Nazanin" size=5>
        <font color=#FF7500>
      آکادمی همراه اول
        </font>
            <br>
        <br>
        دورۀ آشنایی با پایتون
        <br>
        <br>
<b>        آشنایی با کتابخانۀ Numpy
        </b>
        <br>
        <br>
        <b> جمال کزازی <b>
            <p> </p>
    </font>
    </div>
    </div>

<hr>
<font face="B Nazanin"> 
    <h2>
        چرا Numpy؟
    </h2>
    <br>
    <font size=3>
        <p> </p>
کتابخانۀ Numpy یک کتابخانۀ ارزشمند است، به نحوی که می‌تواند برای ما در پایتون آرایه‌ها و ماتریس‌های n-بعدی را مدیریت کند، بسازد و عملیات‌های ریاضی مختلف (ساده تا پیچیده) را بر روی آن‌ها انجام دهد. انعطاف Numpy و افزایش سرعت محاسبات با استفاده از آن باعث مورد توجه گرفتن آن شده است.
        <p></p>
        شاید سوال شود که در مدیریت آرایه‌ها چه تفاوتی بین List در پایتون و Numpy است؟ بهتر است بگوییم که Numpy هم <b> «حافظۀ» </b> کمتری را اشغال می‌کند و هم <b> «سرعت» </b> بیشتری دارد و هم در<b> «اعمال ریاضی و محاسبات» </b> افزونه‌های بسیار زیادی دارد. این تفاوت‌ها باعث شده است که در انجاک محاسبات ماتریسی، Numpy یک جلودار باشد.
        <p></p>
       می‌خواهیم در این دفتر به ساخت آرایه در Numpy و سپس انجام عملیات‌های ریاضی و الگوریتمی مختلف (مثل مرتب کردن، تبدیل فوریه و ...) بپیردازیم.
        <p> </p>
         در اولین قدم به نصب این کتابخانه در پایتون می‌پردازیم:
    </font>
    </font>    

<font face="Consolas">
pip install numpy
    </font>
    <hr>

<font face="B Nazanin">
    <h2>
ساخت آرایه در پایتون با استفاده از Numpy قهرمان!    </h2>
    <br>
    <font size=3>
       برای استفاده از کتابخانه باید در ابتدا آن را import کرد. حال ما می‌خواهیم یک آرایۀ 0-بعدی ایجاد کنیم!
    </font>
    </font>   

In [1]:
import numpy as np

first_array = np.array(100)

print(first_array)

100


<center><img src='n-d-array.png' height=800% width=80%></center>

<font face="B Nazanin">
    <font size=3>
حال می‌خواهیم آرایه‌های 1-بعدی و 2-بعدی و 3-بعدی دلخواه را بسازیم و آن‌ها را چاپ کنیم :) 
        <p></p>
        با استفاده از دستور np.array می‌توان آرایه‌های n-بعدی را نیز ایجاد کرد فقط کمی دقت می‌خواهد و کمی هم باید بازی با براکت‌ها را بلد باشید!
    </font>
    </font> 

In [4]:
array_1d = np.array([1, 2, 3, 4]) # Creating an 1-D array

print(array_1d) 

[1 2 3 4]


In [2]:
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) # Creating a 2-D array

print(array_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
array_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]]) # Creating a 3-D array

print (array_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


<font face="B Nazanin">
    <font size=3>
فرض کنید به شما آرایۀ دلخواهی داده باشند و بخواهید انواع پردازش را بر روی آن انجام دهید. در برخی از پردازش‌ها اگر شما ندانید که بُعد آرایه چقدر است ممکن است به مشکل برخورد کنید. با استفاده از دستور ndim می‌توان تعداد ابعاد آرایه را به‌دست آورد.
    </font>
    </font>   

In [5]:
# print dimension of each array

print (array_1d.ndim)
print (array_2d.ndim)
print (array_3d.ndim)

1
2
3


<hr>
<font face="B Nazanin">
    <h3>
متدهای مختلف ساخت آرایه    </h3>
    <br>
    <font size=3>
        برای ساخت آرایه توسط Numpy متدهای مختلفی وجود دارد. برخی از متدهای معروف عبارتند از: <p> </p> 
        - empty: یک ماتریس empty با ابعاد داده شده ایجاد می‌کند. درایه‌های این ماتریس هر عددی می‌توانند داشته باشند. <br>
        - eye: اگر آرگومان ورودی این متد n باشد، یک ماتریس همانی n در n ایجاد می‌کند. <br>
        - ones: یک ماتریس 1 با ابعاد داده شده ایجاد می‌کند.<br>
        - zeros: یک ماتریس 0 با ابعاد داده شده ایجاد می‌کند.<br>
        - arange: یک آرایه بین دو عدد داده شده با گام مشخص ایجاد می‌کند.<br>
        - linspace: یک آرایه بین دو عدد مشخص شده با تعداد درایه‌های مدنظر ایجاد می‌کند.
    </font>
    </font>   

In [6]:
# create an empty 3*3 matrix
empty_matrix = np.empty([2, 2])
print(empty_matrix)

[[2.12199579e-314 7.53308506e-312]
 [5.63234836e-321 7.53308506e-312]]


In [3]:
# create an eye 3*3 matrix
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# create an ones 3*3 matrix
ones_matrix = np.ones([3, 3])
print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# create a zero 3*3 matrix
zeros_matrix = np.zeros([3, 3])
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# create an array with arange method between 1 and 2 by step 0.05
arange_arr = np.arange(1, 2, 0.05)
print(arange_arr)

[1.   1.05 1.1  1.15 1.2  1.25 1.3  1.35 1.4  1.45 1.5  1.55 1.6  1.65
 1.7  1.75 1.8  1.85 1.9  1.95]


In [11]:
# create an array with linspace method between 1 and 2 with 10 cells
linspace_arr = np.linspace(1, 2, 10)
print(linspace_arr)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


<hr>
<font face="B Nazanin">
    <h3>
متد Meshgrid   </h3>
    <br>
    <font size=3>
        این مند ساخت آرایه معمولا برای ساخت ماتریس‌های n-بعدی استفاده می‌شود. خروجی این متد n بردار یک بعدی است و این مختصات در دستگاه کارتزین ارائه می‌شوند.
    </font>
    </font>   

In [12]:
# create x and y axises
x = np.linspace(-3, 3, 13)
y = np.linspace(-4, 4, 9)

# get two 2-dimensional array
x_mesh, y_mesh = np.meshgrid (x, y)

print (x_mesh)
print ('\n')
print (y_mesh)

[[-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
 [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
 [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
 [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
 [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
 [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
 [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
 [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
 [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]]


[[-4. -4. -4. -4. -4. -4. -4. -4. -4. -4. -4. -4. -4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]


<hr>
<font face="B Nazanin">
    <h3>
تبدیل یک لیست به آرایه‌ای در Numpy   </h3>
    <br>
    <font size=3>
برای این کار کافی است تا لیست را به عنوان آرگومان ورودی تابع array در numpy قرار دهیم.    </font>
    </font>  

In [13]:
List_exp = [1, 2, 4, 8, 16]
np_arr = np.array(List_exp)

print(np_arr)
print (type(np_arr))

[ 1  2  4  8 16]
<class 'numpy.ndarray'>


<hr>
<font face="B Nazanin">
    <h3>
کپی یک آرایه؛ view و copy    </h3>
    <br>
    <font size=3>
برای این که یک آرایه را کپی کنیم راه‌های مختلفی وجود دارد. البته بین این راه‌ها تفاوت‌هایی نیز می‌باشد. اگر همین طور آرایه‌ای را به طور معمول به آرایه‌ای دیگر assign کنیم خواهیم دید که با تغییر آرایه assign شده، آرایۀ اولی نیز تغییر می‌کند. اگر محل ذخیرۀ این دو آرایه را مشاهده کنیم، می‌بینیم که هر دو در یک محل ذخیره شده‌اند. (با استفاده از id)
    </font>
    </font>   

In [7]:
arr1 = np.array([1, 4, 9, 16])
assigned_arr1 = arr1
assigned_arr1[1] = 5

print(arr1)
print(assigned_arr1)

# show memory location of each array
print("id of arr1: ", id(arr1))
print("id of assigned_arr2: ", id(assigned_arr1))

[ 1  5  9 16]
[ 1  5  9 16]
id of arr1:  1621818521232
id of assigned_arr2:  1621818521232


<center><img src='copy_view.jpg' height=50% width=50%></center>

<font face="B Nazanin">
    <font size=3>
حال اگر از مشخصۀ ()view استفاده کنیم خواهیم دید که با تغییر آرایه دومی، آرایه اولی نیز تغییر می‌کند اما محل ذخیرۀ دو آرایه در حافظه متفاوت است.
    </font>
    </font>  

In [9]:
arr2 = np.array ([1, 8, 27, 64])
assigned_arr2 = arr2.view()
assigned_arr2[2] = 125

print(arr2)
print(assigned_arr2)

# show memory location of each array
print("id of arr2: ", id(arr2))
print("id of assigned_arr2: ", id(assigned_arr2))

[  1   8 125  64]
[  1   8 125  64]
id of arr2:  1621818522384
id of assigned_arr2:  1621818522480


<font face="B Nazanin">
    <font size=3>
اما اگر بخواهیم یک آرایه را به نحوی کپی کنیم که آرایه‌ها و تغییراتشان نسبت به هم مستقل باشند از مشخصۀ ()copy استفاده می‌کنیم.
    </font>
    </font>  

In [16]:
arr3 = np.array ([1, 16, 81, 256])
assigned_arr3 = arr3.copy()
assigned_arr3[2] = 625

print(arr3)
print(assigned_arr3)

# show memory location of each array
print("id of arr3: ", id(arr3))
print("id of assigned_arr3: ", id(assigned_arr3))

[  1  16  81 256]
[  1  16 625 256]
id of arr3:  1525463866608
id of assigned_arr3:  1525463912976


<hr>
<font face="B Nazanin">
    <h3>
اضافه کردن درایه به انتهای آرایه    </h3>
    <br>
    <font size=3>
با استفاده از تابع append می‌توان به انتهای یک آرایه، مقادیر دلخواه را اضافه نمود.
    </font>
    </font>   

In [17]:
origin_arr = [1, 2, 3, 4, 5]
append_arr = [10, 11, 12, 13]

final_arr = np.append(origin_arr, append_arr)

print(final_arr)

[ 1  2  3  4  5 10 11 12 13]


<hr>
<font face="B Nazanin">
    <h3>
عوض کردن جای دو سطر یا ستون   </h3>
    <br>
    <font size=3>
اگر بخواهیم جای دو سطر یا ستون را با یکدیگر عوض کنیم باید این تغییرات را مطابق زیر نشان دهیم: 
    </font>
    </font>  

In [15]:
# define an array
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(my_array)

# swap two columns, 0 with 2
my_array[:, [2, 0]] = my_array[:, [0, 2]]
print("\n column 0 swapped with 2:\n", my_array)

# swap two rows, 0 with 2
my_array[[2,0], :] = my_array[[0, 2], :]
print("\n row 0 swapped with 2:\n", my_array)

print(my_array[0][0],my_array[0,0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 column 0 swapped with 2:
 [[ 3  2  1  4]
 [ 7  6  5  8]
 [11 10  9 12]]

 row 0 swapped with 2:
 [[11 10  9 12]
 [ 7  6  5  8]
 [ 3  2  1  4]]
11 11


In [16]:
# define an array
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(my_array)
print(my_array[1][2],my_array[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7 7


<hr>
<font face="B Nazanin">
    <h3>
ادغام آرایه‌ها با یکدیگر   </h3>
    <br>
    <font size=3>
در برخی موارد نیاز است تا دو یا چند آرایه را با یکدیگر ادغام کرد. برای مثال اگر سیگنال 2 صوت مختلف را داشته باشیم و بخواهیم آن‌ها را با هم داشته باشیم باید با هم ادغام کنیم. منظور از ادغام پشت سر هم آوردن آن‌ها است. با استفاده از دستور concatenate می‌توان این کار را انجام داد.
    </font>
    </font>  

In [19]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([6, 7, 8, 9, 10])

arr_3 = np.concatenate((arr_1, arr_2))
print(arr_3)

[ 1  2  3  4  5  6  7  8  9 10]


<font face="B Nazanin">
    <br>
    <font size=3>
حال ممکن است بخواهیم که آرایه‌ها را در محور خاصی با یکدیگر ادغام کنیم. در این صورت از تابع stack استفاده می‌کنیم. برای این که مشخص کنیم در جهت کدام محور می‌خواهیم ادغام صورت بگیرد باید آرگومان axis را مقداردهی کنیم.
    </font>
    </font>  

In [20]:
arr_4 = np.stack((arr_1, arr_2), axis = 0) # merge by row
print("merge by row:\n", arr_4)

arr_5 = np.stack((arr_1, arr_2), axis = 1) # merge by column
print("merge by column:\n", arr_5)

merge by row:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
merge by column:
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


<hr>
<font face="B Nazanin">
    <h3>
مقایسۀ آرایه‌ها با یکدیگر   </h3>
         <font size=3>
          
هنگامی که بخواهیم دو آرایه را با هم مقایسه کنیم که آیا این دو با یکدیگر مساوی هستند یا خیر، می‌توانیم از الگوی زیر استفاده کرد. هم‌چنین علاوه بر الگوی زیر می‌توان از تابع array_equal نیز استفاده کرد. 
    
برای این که درایه‌های دو آرایه را با یکدیگر مقایسه کنیم می‌توانیم از توابع زیر کمک بگیریم:
- greater(a, b): اگر a از b بزرگتر باشد، True است.
            
- greater_equal(a, b): اگر a بزرگتر یا مساوی b باشد، True است.
            
- less(a, b): اگر a کوچکتر از b باشد، True است.
            
- less_equal(a, b): اگر a کوچکتر یا مساوی b باشد، True است.
 
    </font>
    </font>  

In [17]:
arr_1 = np.array([1, 2, 5, 4])
arr_2 = np.array([1, 2, 3, 8])

arr_3 = arr_1 == arr_2 # check equality element-wise
print(arr_3)

equal_arr = arr_3.all() # check two array with eachother 
print(equal_arr)

print(np.array_equal(arr_1, arr_2)) # check two array with eachother by array_equal function

print("a > b  : ", np.greater(arr_1, arr_2)) # a > b
print("a >= b : ", np.greater_equal(arr_1, arr_2)) # a >= b
print("a < b  : ", np.less(arr_1, arr_2)) # a < b
print("a <= b : ", np.less_equal(arr_1, arr_2)) # a <= b

[ True  True False False]
False
False
a > b  :  [False False  True False]
a >= b :  [ True  True  True False]
a < b  :  [False False False  True]
a <= b :  [ True  True False  True]


<hr>
<font face="B Nazanin">
    <h3>
پیدا کردن سطرها، ستون‌ها و المان‌های یکتای آرایه   </h3>
    <br>
    <font size=3>
اگر بخواهیم سطر یکتا، ستون یکتا و یا درایه‌های یکتای یک آرایه را مشخص کنیم می‌توانیم از توابع زیر استفاده کنیم:
        
- unique(array): پیدا کردن درایه‌های یکتا در آرایه
- unique(array, axis=#): پیدا کردن بردار یکتا در مختصات دلخواه 
    </font>
    </font>  

In [22]:
my_array = np.array([[1, 1, 3, 4], [1, 1, 4, 5], [1, 1, 3, 4], [2, 2, 6, 8]])
print("unique elements: ", np.unique(my_array)) # print unique elements
print("unique vectors of array in axis 0: \n", np.unique(my_array, axis = 0)) # print unique vectors in axis 0
print("unique vectors of array in axis 1: \n", np.unique(my_array, axis =1)) # print unique vectors in axis 1

unique elements:  [1 2 3 4 5 6 8]
unique vectors of array in axis 0: 
 [[1 1 3 4]
 [1 1 4 5]
 [2 2 6 8]]
unique vectors of array in axis 1: 
 [[1 3 4]
 [1 4 5]
 [1 3 4]
 [2 6 8]]


<hr>
<font face="B Nazanin">
    <h3>
حذف صفرهای ابتدا و انتهای آرایه   </h3>
    <br>
    <font size=3>
اگر سیگنالی را ذخیره کنیم در ابتدا و انتهای سیگنال تعدادی صفر وجود دارد. در برخی اوقات این صفرها را باید حذف کرد یا این که بهتر است که حذف کنیم. با استفاده از تابع trim_zeros می‌توان این کار را انجام داد. 
    </font>
    </font>  

In [23]:
my_array = np.array([0, 0, 0, 0, 1, 2, 3, 0, 0, 4, 0, 0])
new_array = np.trim_zeros(my_array)
print(new_array)

[1 2 3 0 0 4]


<hr>
<font face="B Nazanin">
    <h2>
عملیات‌های باینری   
      </h2>
    <br>
    <font size=3>
        
عملیات‌های باینری عمدتا از نوع bitwise هستند و برخی از آن‌ها عبارتند از:

- bitwise_and: این تابع بیت به بیت المان‌های هم ایندکس را با هم AND می‌کند.
- bitwise_or: این تابع بیت به بیت المان‌های هم ایندکس را با هم OR می‌کند.
- bitwise_xor: این تابع بیت به بیت المان‌های هم ایندکس را با هم XOR می‌کند.
- invert: این تابع بیت‌های هر کدام از المان‌ها را NOT می‌کند.
- left_shift: این تابع بیت‌های هر المان را به چپ شیفت می‌دهد.
- right_shift: این تابع بیت‌های هر المان را به راست شیفت می‌دهد.
- binary_repr: این تابع باینری هر المان را نشان می‌دهد.

    </font>
    </font>  

In [24]:
arr_1 = np.array([1, 2, 3, 4, 9, 13])
arr_2 = np.array([1, 2, 6, 20, 14, 25])

print("Bitwise AND: ", np.bitwise_and(arr_1, arr_2))
print("Bitwise OR:  ", np.bitwise_or(arr_1, arr_2))
print("Bitwise XOR: ", np.bitwise_xor(arr_1, arr_2))
print("Bitwise NOT: ", np.invert(arr_1, arr_2))
print("Bitwise AND: ", np.bitwise_and(arr_1, arr_2))
print("\n\nLeft shift arr_1 with 2bits:   ", np.left_shift(arr_1, 2))
print("Right shift arr_1 with 2bits:  ", np.right_shift(arr_1, 2))

Bitwise AND:  [1 2 2 4 8 9]
Bitwise OR:   [ 1  2  7 20 15 29]
Bitwise XOR:  [ 0  0  5 16  7 20]
Bitwise NOT:  [ -2  -3  -4  -5 -10 -14]
Bitwise AND:  [0 0 0 0 0 0]


Left shift arr_1 with 2bits:    [ 4  8 12 16 36 52]
Right shift arr_1 with 2bits:   [0 0 0 1 2 3]


<hr>
<font face="B Nazanin">
    <h2>
عملیات‌های ریاضیاتی  
      </h2>
    <br>
    <font size=3>
        
<h3>
    توابع مثلثاتی
        </h3>

توابع مثلثاتی معروف در کتابخانۀ numpy تعریف شده و عبارتند از:
        
- sin
- cos
- tan
- arcsin
- arccos 
- arctan
- rad2deg: تبدیل رادیان به درجه
- deg2rad: تبدیل درجه به رادیان
    </font>
    </font>  

In [25]:
signal_array = np.array([0.01, 0.1, 0.3, 0.45, 0.56, 0.87])
print("Sin of array: ", np.sin(signal_array))
print("Cos of array: ", np.cos(signal_array))
print("Tan of array: ", np.tan(signal_array))
print("Arcsin of array: ", np.arcsin(signal_array))
print("Arccos of array: ", np.arccos(signal_array))
print("Arctan of array: ", np.arctan(signal_array))
print("Change radian to degree of array: ", np.rad2deg(signal_array))
print("Change degree to radian of array: ", np.deg2rad(signal_array))

Sin of array:  [0.00999983 0.09983342 0.29552021 0.43496553 0.5311862  0.76432894]
Cos of array:  [0.99995    0.99500417 0.95533649 0.9004471  0.84725511 0.64482655]
Tan of array:  [0.01000033 0.10033467 0.30933625 0.48305507 0.62694954 1.18532486]
Arcsin of array:  [0.01000017 0.10016742 0.30469265 0.46676534 0.5943858  1.05520232]
Arccos of array:  [1.56079616 1.47062891 1.26610367 1.10403099 0.97641053 0.51559401]
Arctan of array:  [0.00999967 0.09966865 0.29145679 0.42285393 0.51048832 0.71599111]
Change radian to degree of array:  [ 0.5729578   5.72957795 17.18873385 25.78310078 32.08563653 49.84732818]
Change degree to radian of array:  [0.00017453 0.00174533 0.00523599 0.00785398 0.00977384 0.01518436]


<font face="B Nazanin">
    <br>
    <font size=3>
        
<h3>
توابع هایپربولیک        </h3>

توابع هایپربولیک معروف در کتابخانۀ numpy تعریف شده و عبارتند از:
        
- sinh
- cosh
- tanh
- arcsinh
- arccosh
- arctanh
    </font>
    </font>  

In [26]:
print("Sinh of array: ", np.sinh(signal_array))
print("Cosh of array: ", np.cosh(signal_array))
print("Tanh of array: ", np.tanh(signal_array))
print("Arcsinh of array: ", np.arcsinh(signal_array))
print("Arccosh of array: ", np.arccosh(signal_array * 100)) # cosh is over 1 so we multiple signal_array *100
print("Arctanh of array: ", np.arctanh(signal_array))

Sinh of array:  [0.01000017 0.10016675 0.30452029 0.46534202 0.58973172 0.98397965]
Cosh of array:  [1.00005    1.00500417 1.04533851 1.10297017 1.16094078 1.4029312 ]
Tanh of array:  [0.00999967 0.09966799 0.29131261 0.42189901 0.50797743 0.70137413]
Arcsinh of array:  [0.00999983 0.09983408 0.29567305 0.43604967 0.53422407 0.78640118]
Arccosh of array:  [0.         2.99322285 4.09406667 4.49968619 4.71841914 5.15902227]
Arctanh of array:  [0.01000033 0.10033535 0.3095196  0.48470028 0.63283319 1.33307963]


<hr>
<font face="B Nazanin">
    <h2>
جبر خطی با Numpy!  
      </h2>
    <br>
    <font size=3>
اعمال مختلفی می‌توان بر روی یک ماتریس انجام داد. برای مثال می‌توان دترمینان آن را حساب کرد و یا در صورت لزوم معکوس آن را به دست آورد. توابعی که در جبر خطی می‌توان نام برد از این قرارند:
        
- linalg.det: محاسبۀ دترمینان ماتریس
- linalg.inv: محاسبۀ معکوس تابع
- linalg.eigvals: به‌دست آوردن مقادیر ویژه ماتریس
- dot: ضرب داخلی آرایه
- inner: ضرب داخلی آرایه
- outer: ضرب خارجی آرایه
- linalg.solve(a, b): حل معادلۀ a*x = b با استفاده از ماتریس‌های a و b
- linalg.norm: محاسبۀ نُرم ماتریس
    </font>
    </font>  

In [27]:
a = np.array([[1, 2, 3], [4, 4, 6], [2, 5, 10]])
b = np.array([6, 7, 8])
arr_1 = [1, 2, 3, 4]
arr_2 = [1, 5, 3, 6]
print("Determinant: ", np.linalg.det(a))
print("Inverse: \n", np.linalg.inv(a))
print("Eigen values: \n", np.linalg.eigvals(a))
print("\nInner product of arr_1 and arr_2: ", np.dot(arr_1, arr_2))
print("\nInner product of arr_1 and arr_2: ", np.inner(arr_1, arr_2))
print("\nOuter product of arr_1 and arr_2: \n", np.outer(arr_1, arr_2))
print("\nResult of 'a * x = b' equation: ", np.linalg.solve(a, b))
print("Norm of 'a' matrix: ", np.linalg.norm(a))

Determinant:  -9.999999999999998
Inverse: 
 [[-1.   0.5  0. ]
 [ 2.8 -0.4 -0.6]
 [-1.2  0.1  0.4]]
Eigen values: 
 [14.24894017 -0.54252744  1.29358727]

Inner product of arr_1 and arr_2:  44

Inner product of arr_1 and arr_2:  44

Outer product of arr_1 and arr_2: 
 [[ 1  5  3  6]
 [ 2 10  6 12]
 [ 3 15  9 18]
 [ 4 20 12 24]]

Result of 'a * x = b' equation:  [-2.5  9.2 -3.3]
Norm of 'a' matrix:  14.52583904633395


<hr>
<font face="B Nazanin">
    <h2>
ابعاد یک ماتریس
    </h2>
    <br>
    <font size=3>
زمانی که یک ماتریس به ما داده شد (که احتمال زیاد حاوی یک سیگنال و یا مجموعه‌ای از داده‌ها است!) برای تجزیه و تحلیل آن سریعا ابعاد آن را به‌دست می‌آوریم! :) برای به‌دست آوردن ابعاد از مشخصۀ shape استفاده می‌کنیم. 
    </font>
    </font>  

In [19]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("shape of array: ", array.shape)

shape of array:  (3, 4)


<font face="B Nazanin">
    <h2>
تغییر ابعاد یک ماتریس
    </h2>
    <br>
    <font size=3>
حال ممکن است بخواهیم یک ماتریس از ابعاد مورد نظر به ابعاد دیگری ببریم. برای مثال ماتریس m*n است، حال می‌خواهیم ابعاد را به k*l تغییر دهیم. این عملیات با استفاده از مشخصۀ reshape صورت می‌گیرد.
        
اگر بخواهیم آرایه با هر ابعادی را به آرایه‌ای یک بعدی تبدیل کنیم از دستور reshape(-1) استفاده می‌کنیم.
    </font>
    </font> 

In [20]:
print("new shape of array: \n", array.reshape(6, 2)) # convert 3*4 array to 6*2
print("\n2-d to 3-d conversion: \n", array.reshape(2, 2, 3)) # convert 2-d to 3-d 
print("\n1-d conversion of array: ", array.reshape(-1))

new shape of array: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

2-d to 3-d conversion: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1-d conversion of array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]


<hr>
<font face="B Nazanin">
    <h2>
تکرار بر روی آرایه (Iterating)
    </h2>
    <br>
    <font size=3>
منظور از تکرار بر روی آرایه آن است که اعضای آرایه یک به یک پیموده شود. در ابتدا به تکرار بر روی آرایۀ 1-بعدی می‌پردازیم:
    </font>
    </font> 

In [30]:
my_array = np.array([1, 2, 3, 4, 5])
for i in my_array:
    print(i)

1
2
3
4
5


<font face="B Nazanin">
    <br>
    <font size=3>
قضیه برای آرایه‌های 2-بعدی فرق می‌کند و اگر تنها یک حلقه برای پیمایش استفاده شود، ردیف‌ها چاپ می‌شوند. برای این که تک تک درایه‌های آرایۀ 2-بعدی را چاپ کنیم از دو حلقۀ تو در تو استفاده می‌کنیم.
    </font>
    </font> 

In [33]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# print rows
for i in my_array:
    print(i)

# print elements
for i in my_array:
    for j in i:
        print(j)

[1 2 3 4]
[5 6 7 8]
1
2
3
4
5
6
7
8


<hr>
<font face="B Nazanin">
    <h2>
جست‌وجو در آرایه‌ها
    </h2>
    <br>
    <font size=3>
اگر به دنبال آن هستیم که در چه اندیس‌هایی مقادیری هستند که شرایط دلخواه ما را داشته باشند از متد where استفاده می‌کنیم. منظور از هر شرطی، یک شرط منطقی است که در مثال زیر خواهیم دید.    </font>
    </font> 

In [35]:
my_array = np.array([20, 15, 17, 18, 19, 18.5, 17.5, 16, 13, 12, 11])
val_list = np.where(my_array > 15) # elements that are bigger than 15
val_list_1 = np.where(my_array == 18) # elements that are equal to 18
print(val_list)
print(val_list_1)

(array([0, 2, 3, 4, 5, 6, 7], dtype=int64),)
(array([3], dtype=int64),)


<hr>
<font face="B Nazanin">
    <h2>
مرتب‌سازی آرایه‌ها
    </h2>
    <br>
    <font size=3>
برای آن که یک آرایه را مرتب کنیم از متد sort استفاده می‌کنیم. sort می‌تواند برای اعداد، رشته‌ها و حتی متغیرهای منطقی(boolean) استفاده شود. اگر برای آرایه‌های 2-بعدی استفاده شود، مرتب‌سازی در هر ردیف انجام می‌شود.
    </font>
    </font> 

In [42]:
my_array = np.array([2, 1, 8, 6, 3, 7, 4])
sorted_array = np.sort(my_array) # sort array
print(sorted_array, '\n')

my_array_1 = np.array([[3, 2, 1, 5], [6, 4, 5, 8]]) # sort 2-d array
print(np.sort(my_array_1))

[1 2 3 4 6 7 8] 

[[1 2 3 5]
 [4 5 6 8]]


<hr>
<font face="B Nazanin">
    <h2>
فیلتر آرایه‌ها
    </h2>
    <br>
    <font size=3>
وقتی صحبت از فیلتر می‌شود منظور آن است که از یک آرایۀ موجود درایه‌هایی را خارج کرده و با آن یک آرایۀ جدید ساخته شود. در Numpy با استفاده از اندیس‌گذاری boolean می‌توان این کار را انجام داد. یعنی آرایه‌ای به نام آرایۀ فیلتر ساخته شود و مطابق آن فیلتر صورت می‌گیرد.
    </font>
    </font> 

In [44]:
my_array = np.array([10, 15, 16, 20, 18, 19])

# first solution
filter_ = [False, False, True, True, True, True]
filtered_array = my_array[filter_]
print(filtered_array)

# second solution
filter_ = []
for i in my_array:
    if (i 2 > 15):
        filter_.append(True)
    else:
        filter_.append(False)

filtered_array = my_array[filter_]
print(filtered_array)

[16 20 18 19]
[16 20 18 19]
